const info = {
  id: 'tt11866324',
  title: 'Prey',
  originalTitle: '',
  fullTitle: 'Prey (2022)',
  type: 'Movie',
  year: '2022',
  image:
    'https://m.media-amazon.com/images/M/MV5BMDBlMDYxMDktOTUxMS00MjcxLWE2YjQtNjNhMjNmN2Y3ZDA1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_Ratio0.6762_AL_.jpg',
  releaseDate: '2022-08-05',
  runtimeMins: '99',
  runtimeStr: '1h 39min',
  plot: 'The origin story of the Predator in the world of the Comanche Nation 300 years ago. Naru, a skilled warrior, fights to protect her tribe against one of the first highly-evolved Predators to land on Earth.',
  plotLocal: '',
  plotLocalIsRtl: false,
  awards: '',
  directors: 'Dan Trachtenberg',
  directorList: [{ id: 'nm0870469', name: 'Dan Trachtenberg' }],
  writers: 'Patrick Aison, Dan Trachtenberg, Jim Thomas',
  writerList: [
    { id: 'nm1725034', name: 'Patrick Aison' },
    { id: 'nm0870469', name: 'Dan Trachtenberg' },
    { id: 'nm0859029', name: 'Jim Thomas' },
  ],
  stars: 'Amber Midthunder, Dakota Beavers, Dane DiLiegro',
  starList: [
    { id: 'nm1690270', name: 'Amber Midthunder' },
    { id: 'nm13396806', name: 'Dakota Beavers' },
    { id: 'nm10867068', name: 'Dane DiLiegro' },
  ],
  actorList: [
    {
      id: 'nm1690270',
      image:
        'https://m.media-amazon.com/images/M/MV5BNjMwYjI1ZTctZGE5My00M2RmLTgxNzktMmZkN2I3M2Q5MTE5XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg',
      name: 'Amber Midthunder',
      asCharacter: 'Naru',
    },
    {
      id: 'nm13396806',
      image:
        'https://m.media-amazon.com/images/M/MV5BN2YzZGNmZmYtZTc4MS00MTRiLWEyOTMtZTQ0MDE5ZjMzYzU0XkEyXkFqcGdeQXVyMTUyOTU1Njg4._V1_Ratio1.0714_AL_.jpg',
      name: 'Dakota Beavers',
      asCharacter: 'Taabe',
    },
    {
      id: 'nm10867068',
      image:
        'https://m.media-amazon.com/images/M/MV5BZmIwNmM0YjgtODcwZi00MWZjLTg5ZTEtNjNkOTVhOTlkMzMzXkEyXkFqcGdeQXVyMTA1OTE0NDgz._V1_Ratio1.2571_AL_.jpg',
      name: 'Dane DiLiegro',
      asCharacter: 'Predator',
    },
    {
      id: 'nm11901532',
      image:
        'https://m.media-amazon.com/images/M/MV5BOTkzODBiM2ItODdmOS00YTUxLThmM2ItZmVlOTE4NWM3ZTFkXkEyXkFqcGdeQXVyMTUxNzkwNTg5._V1_Ratio1.0000_AL_.jpg',
      name: 'Stormee Kipp',
      asCharacter: 'Wasape',
    },
    {
      id: 'nm0861969',
      image:
        'https://m.media-amazon.com/images/M/MV5BNjc2ODE4NjY3MV5BMl5BanBnXkFtZTcwNzE2NzM1OQ@@._V1_Ratio1.3857_AL_.jpg',
      name: 'Michelle Thrush',
      asCharacter: 'Aruka',
    },
    {
      id: 'nm2539870',
      image:
        'https://m.media-amazon.com/images/M/MV5BMTYzYjIwOTItNjI2ZC00YmE5LTk2MzQtZjA5ODliOTY2ZmUwXkEyXkFqcGdeQXVyMjMzNjY2MDU@._V1_Ratio1.0000_AL_.jpg',
      name: 'Julian Black Antelope',
      asCharacter: 'Chief Kehetu',
    },
    {
      id: 'nm0558774',
      image:
        'https://m.media-amazon.com/images/M/MV5BMTYxOTE0MjA4N15BMl5BanBnXkFtZTYwNDA4Mjgy._V1_Ratio1.0000_AL_.jpg',
      name: 'Stefany Mathias',
      asCharacter: 'Sumu (Chief Wife)',
    },
    {
      id: 'nm7121620',
      image:
        'https://m.media-amazon.com/images/M/MV5BYjNjZmQ0ZTUtMDQxYS00MWRiLThiOTgtNTRlMDE1ZmVkODVjXkEyXkFqcGdeQXVyNjAyNDEzNzU@._V1_Ratio1.0000_AL_.jpg',
      name: 'Bennett Taylor',
      asCharacter: 'Raphael',
    },
    {
      id: 'nm1116945',
      image:
        'https://m.media-amazon.com/images/M/MV5BMDg1Y2U2NDItNzA0Yy00ODlmLTkwZDgtNzgwZjkyMTdhYTIxXkEyXkFqcGdeQXVyMjAwMjgwNDA@._V1_Ratio1.0000_AL_.jpg',
      name: 'Mike Paterson',
      asCharacter: 'Big Beard',
    },
    {
      id: 'nm1692766',
      image:
        'https://m.media-amazon.com/images/M/MV5BMjllNjAyYzktM2E5NS00ZTcxLTg5OTUtNmI3MDEzY2E1NTE2XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg',
      name: 'Nelson Leis',
      asCharacter: 'Waxed Mustache',
    },
    {
      id: 'nm13297228',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Tymon Carter',
      asCharacter: 'Huupi',
    },
    {
      id: 'nm8702912',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Skye Pelletier',
      asCharacter: 'Tabu',
    },
    {
      id: 'nm12388460',
      image:
        'https://m.media-amazon.com/images/M/MV5BZTMwNTg4YWMtNDgyZC00OGQ0LTk2ZjEtZTBlMDg0OTc0ZWVkXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_Ratio1.5000_AL_.jpg',
      name: 'Harlan Blayne Kytwayhat',
      asCharacter: 'Itsee',
    },
    {
      id: 'nm10970427',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Corvin Mack',
      asCharacter: 'Paaka',
    },
    {
      id: 'nm6754843',
      image:
        'https://m.media-amazon.com/images/M/MV5BNDI4NjE4NTYzN15BMl5BanBnXkFtZTgwMTkwNTcyNDM@._V1_Ratio1.0000_AL_.jpg',
      name: 'Samuel Marty',
      asCharacter: 'Puhi',
    },
    {
      id: 'nm13905778',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Ginger Cattleman',
      asCharacter: 'Disapproving Woman',
    },
    {
      id: 'nm13905779',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Seanna Eagletail',
      asCharacter: 'Young Comanche Woman',
    },
    {
      id: 'nm13898988',
      image: 'https://imdb-api.com/images/original/nopicture.jpg',
      name: 'Samiyah Crowfoot',
      asCharacter: 'Young Comanche Girl',
    },
  ],
  fullCast: null,
  genres: 'Action, Adventure, Drama',
  genreList: [
    { key: 'Action', value: 'Action' },
    { key: 'Adventure', value: 'Adventure' },
    { key: 'Drama', value: 'Drama' },
  ],
  companies:
    '20th Century Studios, Davis Entertainment, Lawrence Gordon Productions',
  companyList: [
    { id: 'co0781821', name: '20th Century Studios' },
    { id: 'co0022730', name: 'Davis Entertainment' },
    { id: 'co0041635', name: 'Lawrence Gordon Productions' },
  ],
  countries: 'USA',
  countryList: [{ key: 'USA', value: 'USA' }],
  languages: 'English, North American Indian, French',
  languageList: [
    { key: 'English', value: 'English' },
    { key: 'North American Indian', value: 'North American Indian' },
    { key: 'French', value: 'French' },
  ],
  contentRating: 'R',
  imDbRating: '7.2',
  imDbRatingVotes: '116785',
  metacriticRating: '71',
  ratings: null,
  wikipedia: null,
  posters: {
    imDbId: 'tt11866324',
    title: 'Prey',
    fullTitle: 'Prey (2022)',
    type: 'Movie',
    year: '2022',
    posters: [
      {
        id: 'cv6zBbPfP0MMxgMdve95YrIIQwq.jpg',
        link: 'https://image.tmdb.org/t/p/original/cv6zBbPfP0MMxgMdve95YrIIQwq.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: 'ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
        link: 'https://image.tmdb.org/t/p/original/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1800,
        height: 2700,
      },
      {
        id: 'h58U7d1OZyuWaCWMYvw4mfnv6H3.jpg',
        link: 'https://image.tmdb.org/t/p/original/h58U7d1OZyuWaCWMYvw4mfnv6H3.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1320,
        height: 1980,
      },
      {
        id: 'rvsiHlXOWlaizQh7HsL6ZJwsbMj.jpg',
        link: 'https://image.tmdb.org/t/p/original/rvsiHlXOWlaizQh7HsL6ZJwsbMj.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: '1zsi3REYSLqJmNk44FNIZzU7VSS.jpg',
        link: 'https://image.tmdb.org/t/p/original/1zsi3REYSLqJmNk44FNIZzU7VSS.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1000,
        height: 1500,
      },
      {
        id: 'snQsveePmfS0fajc10ymv9ewd4o.jpg',
        link: 'https://image.tmdb.org/t/p/original/snQsveePmfS0fajc10ymv9ewd4o.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: 'w0SmlSPVodSDGtaZweYD1KBFOUN.jpg',
        link: 'https://image.tmdb.org/t/p/original/w0SmlSPVodSDGtaZweYD1KBFOUN.jpg',
        aspectRatio: 0.6748046875,
        language: 'en',
        width: 1382,
        height: 2048,
      },
      {
        id: 'Adp8OoGWvBXDc9EPdMaEtq9xNwx.jpg',
        link: 'https://image.tmdb.org/t/p/original/Adp8OoGWvBXDc9EPdMaEtq9xNwx.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 784,
        height: 1176,
      },
      {
        id: '5MGfSQPbg7rug2EvfgTwvzyKFC8.jpg',
        link: 'https://image.tmdb.org/t/p/original/5MGfSQPbg7rug2EvfgTwvzyKFC8.jpg',
        aspectRatio: 0.6782729805013927,
        language: 'en',
        width: 974,
        height: 1436,
      },
      {
        id: '7RyL4LVB12umzxMHjiiBcv7vucn.jpg',
        link: 'https://image.tmdb.org/t/p/original/7RyL4LVB12umzxMHjiiBcv7vucn.jpg',
        aspectRatio: 0.6664411366711772,
        language: 'en',
        width: 985,
        height: 1478,
      },
      {
        id: '64WNM9whvRG1r8pr0bI0CBLV1Jn.jpg',
        link: 'https://image.tmdb.org/t/p/original/64WNM9whvRG1r8pr0bI0CBLV1Jn.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: 'oJqxxQJv0AOQFttNo1FAvzQqCSj.jpg',
        link: 'https://image.tmdb.org/t/p/original/oJqxxQJv0AOQFttNo1FAvzQqCSj.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: '6YnnkoWurVD9ByzWZIGOC6v5qHQ.jpg',
        link: 'https://image.tmdb.org/t/p/original/6YnnkoWurVD9ByzWZIGOC6v5qHQ.jpg',
        aspectRatio: 0.7009443861490031,
        language: 'en',
        width: 668,
        height: 953,
      },
      {
        id: 'hRtI9YdgW21RlQJJXrzGO9zNZ8O.jpg',
        link: 'https://image.tmdb.org/t/p/original/hRtI9YdgW21RlQJJXrzGO9zNZ8O.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: 'rF8lDf3Gblgghp5UVuQ22BnwAYw.jpg',
        link: 'https://image.tmdb.org/t/p/original/rF8lDf3Gblgghp5UVuQ22BnwAYw.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1000,
        height: 1500,
      },
      {
        id: 'mCjwHHZ0ogLHkD85XGtG6AdVvUz.jpg',
        link: 'https://image.tmdb.org/t/p/original/mCjwHHZ0ogLHkD85XGtG6AdVvUz.jpg',
        aspectRatio: 0.675,
        language: 'en',
        width: 1296,
        height: 1920,
      },
      {
        id: 'l1QhkXmZlKFUzcp3ZvuOph2V4S4.jpg',
        link: 'https://image.tmdb.org/t/p/original/l1QhkXmZlKFUzcp3ZvuOph2V4S4.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1000,
        height: 1500,
      },
      {
        id: 'eyydpo30sxrtu1znwmeiaumh6HM.jpg',
        link: 'https://image.tmdb.org/t/p/original/eyydpo30sxrtu1znwmeiaumh6HM.jpg',
        aspectRatio: 0.7496617050067659,
        language: 'en',
        width: 1108,
        height: 1478,
      },
      {
        id: 'beiBYo7X0yPu2wSECSW0uuch5ps.jpg',
        link: 'https://image.tmdb.org/t/p/original/beiBYo7X0yPu2wSECSW0uuch5ps.jpg',
        aspectRatio: 0.6751343429408891,
        language: 'en',
        width: 1382,
        height: 2047,
      },
      {
        id: '7X1exnRCg3jcukCOwNoAXtGjXAr.jpg',
        link: 'https://image.tmdb.org/t/p/original/7X1exnRCg3jcukCOwNoAXtGjXAr.jpg',
        aspectRatio: 0.6754545454545454,
        language: 'en',
        width: 743,
        height: 1100,
      },
      {
        id: 'x2kR1gMKTZedimKneeoYp8A3wt4.jpg',
        link: 'https://image.tmdb.org/t/p/original/x2kR1gMKTZedimKneeoYp8A3wt4.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
      {
        id: 'x6JJuwNpVbynypYrRkqAMga6Bld.jpg',
        link: 'https://image.tmdb.org/t/p/original/x6JJuwNpVbynypYrRkqAMga6Bld.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1200,
        height: 1800,
      },
      {
        id: 'gcBLhSzlyVzuAX0FauMKXcQdOoE.jpg',
        link: 'https://image.tmdb.org/t/p/original/gcBLhSzlyVzuAX0FauMKXcQdOoE.jpg',
        aspectRatio: 0.6788025889967637,
        language: 'en',
        width: 839,
        height: 1236,
      },
      {
        id: 'hsuZEE8k0fEh4G4o6PBbNCLdAhH.jpg',
        link: 'https://image.tmdb.org/t/p/original/hsuZEE8k0fEh4G4o6PBbNCLdAhH.jpg',
        aspectRatio: 0.6788025889967637,
        language: 'en',
        width: 839,
        height: 1236,
      },
      {
        id: 'fwZrvjroGe4hzjjEz6Dy4viqNeA.jpg',
        link: 'https://image.tmdb.org/t/p/original/fwZrvjroGe4hzjjEz6Dy4viqNeA.jpg',
        aspectRatio: 0.6788025889967637,
        language: 'en',
        width: 839,
        height: 1236,
      },
      {
        id: 'yn2YSr4FECSIfBoSkmvS6Ksx7K4.jpg',
        link: 'https://image.tmdb.org/t/p/original/yn2YSr4FECSIfBoSkmvS6Ksx7K4.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 1000,
        height: 1500,
      },
      {
        id: '7pzNzVBLfenqiQ8lsAxKp49HPFa.jpg',
        link: 'https://image.tmdb.org/t/p/original/7pzNzVBLfenqiQ8lsAxKp49HPFa.jpg',
        aspectRatio: 0.6666666666666666,
        language: 'en',
        width: 2000,
        height: 3000,
      },
    ],
    backdrops: [
      {
        id: '7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
        link: 'https://image.tmdb.org/t/p/original/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 3840,
        height: 2160,
      },
      {
        id: 'keBPoGFL8iTJWvJ28CqaGYR92BX.jpg',
        link: 'https://image.tmdb.org/t/p/original/keBPoGFL8iTJWvJ28CqaGYR92BX.jpg',
        aspectRatio: 1.7772511848341233,
        language: 'en',
        width: 3000,
        height: 1688,
      },
      {
        id: 'sNhzcUw5cg4JwICjnHZ5XhTKNrU.jpg',
        link: 'https://image.tmdb.org/t/p/original/sNhzcUw5cg4JwICjnHZ5XhTKNrU.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 3840,
        height: 2160,
      },
      {
        id: 'aGocH8JGZXFG8MtpmvGcAgwnJ5O.jpg',
        link: 'https://image.tmdb.org/t/p/original/aGocH8JGZXFG8MtpmvGcAgwnJ5O.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 3840,
        height: 2160,
      },
      {
        id: '2m86A5G4yTVHe1N9LwzDbMon6mQ.jpg',
        link: 'https://image.tmdb.org/t/p/original/2m86A5G4yTVHe1N9LwzDbMon6mQ.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 3840,
        height: 2160,
      },
      {
        id: '9FXGnVz3JwJ4KEY4eUoSEK4tvva.jpg',
        link: 'https://image.tmdb.org/t/p/original/9FXGnVz3JwJ4KEY4eUoSEK4tvva.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 1280,
        height: 720,
      },
      {
        id: 'ajok0M9j7sAGhFp6clKUGJ6KaRl.jpg',
        link: 'https://image.tmdb.org/t/p/original/ajok0M9j7sAGhFp6clKUGJ6KaRl.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 2048,
        height: 1152,
      },
      {
        id: 'udhU4oOPxAiNltoMVddSRq3lLAk.jpg',
        link: 'https://image.tmdb.org/t/p/original/udhU4oOPxAiNltoMVddSRq3lLAk.jpg',
        aspectRatio: 1.7773148148148148,
        language: 'en',
        width: 3839,
        height: 2160,
      },
      {
        id: 'yw55Jqd0PPt84xTRCV5Ve9S1Rfs.jpg',
        link: 'https://image.tmdb.org/t/p/original/yw55Jqd0PPt84xTRCV5Ve9S1Rfs.jpg',
        aspectRatio: 1.7777777777777777,
        language: 'en',
        width: 1280,
        height: 720,
      },
    ],
    errorMessage: '',
  },
  images: {
    imDbId: 'tt11866324',
    title: 'Prey',
    fullTitle: 'Prey (2022)',
    type: 'Movie',
    year: '2022',
    items: [
      {
        title: 'Amber Midthunder in Prey (2022)',
        image:
          'https://imdb-api.com/images/original/MV5BYjkzNTRiMDQtZDZhNS00NjNhLWJhM2ItNDFmNjhiYzRiN2RmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio1.7800_AL_.jpg',
      },
      {
        title: 'Amber Midthunder in Prey (2022)',
        image:
          'https://imdb-api.com/images/original/MV5BODBiOGYzZDQtOGIxNy00YzA3LTkwMTgtZjFhMzFjMDU4ODAxXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_Ratio1.4400_AL_.jpg',
      },
      {
        title: 'Prey (2022)',
        image:
          'https://imdb-api.com/images/original/MV5BNTY1NzFlNDktMWY4OS00YmFhLTg1NDgtZTRmODczNzQxNjE2XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_Ratio1.4800_AL_.jpg',
      },
      {
        title: 'Amber Midthunder in Prey (2022)',
        image:
          'https://imdb-api.com/images/original/MV5BYzI0NzZhMDMtNTMwYy00MTAzLWExOTEtNWU0ZjIxYmZjY2JkXkEyXkFqcGdeQXVyMjkyMTAxMw@@._V1_Ratio1.0000_AL_.jpg',
      },
    ],
    errorMessage: '',
  },
  trailer: {
    imDbId: 'tt11866324',
    title: 'Prey',
    fullTitle: 'Prey (2022)',
    type: 'Movie',
    year: '2022',
    videoId: 'vi1860878873',
    videoTitle: 'Official Trailer',
    videoDescription:
      'The origin story of the Predator in the world of the Comanche Nation 300 years ago. Naru, a skilled female warrior, fights to protect her tribe against one of the first highly-evolved Predators to land on Earth.',
    thumbnailUrl:
      'https://m.media-amazon.com/images/M/MV5BYWRmYzZkMzAtYTc4ZC00NjI4LTg1ZjEtZTAyOTJmYmZiOGIxXkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg',
    uploadDate: null,
    link: 'https://www.imdb.com/video/vi1860878873',
    linkEmbed: 'https://www.imdb.com/video/imdb/vi1860878873/imdb/embed',
    errorMessage: '',
  },
  boxOffice: {
    budget: '',
    openingWeekendUSA: '',
    grossUSA: '',
    cumulativeWorldwideGross: '',
  },
  tagline: null,
  keywords: 'comanche,predator,hunting,warrior,prequel',
  keywordList: ['comanche', 'predator', 'hunting', 'warrior', 'prequel'],
  similars: [
    {
      id: 'tt0093773',
      title: 'Predator',
      image:
        'https://m.media-amazon.com/images/M/MV5BY2QwYmFmZTEtNzY2Mi00ZWMyLWEwY2YtMGIyNGZjMWExOWEyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.8',
    },
    {
      id: 'tt1424381',
      title: 'Predators',
      image:
        'https://m.media-amazon.com/images/M/MV5BNjFmNDNlMGItMDQxMS00ZWMxLTg4MmQtMTBiNWU3ZDU1Nzk1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '6.4',
    },
    {
      id: 'tt0100403',
      title: 'Predator 2',
      image:
        'https://m.media-amazon.com/images/M/MV5BNThjZjI4NTgtZDk4Mi00ZjI1LWExZGUtNTRkOWY1ZTY3M2FlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '6.3',
    },
    {
      id: 'tt1751634',
      title: 'The Sandman',
      image:
        'https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.8',
    },
    {
      id: 'tt1649418',
      title: 'The Gray Man',
      image:
        'https://m.media-amazon.com/images/M/MV5BOWY4MmFiY2QtMzE1YS00NTg1LWIwOTQtYTI4ZGUzNWIxNTVmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '6.5',
    },
    {
      id: 'tt12262116',
      title: 'Thirteen Lives',
      image:
        'https://m.media-amazon.com/images/M/MV5BNzI4YzkyMTYtYmQ1MC00NjYwLThkMDgtY2E1Njg1MTAzZWJhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.8',
    },
    {
      id: 'tt13314558',
      title: 'Day Shift',
      image:
        'https://m.media-amazon.com/images/M/MV5BYWI2ZDRjYjEtOWJiOS00NWVjLWI1MjAtNWNiMzAwNGFmNjljXkEyXkFqcGdeQXVyODEwMTc2ODQ@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '6.1',
    },
    {
      id: 'tt3829266',
      title: 'The Predator',
      image:
        'https://m.media-amazon.com/images/M/MV5BNjZjN2QzNjYtYWZkMi00OWQ4LWFjNDctYjcyMjM2ZDNjOWMyXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '5.3',
    },
    {
      id: 'tt0370263',
      title: 'Alien vs. Predator',
      image:
        'https://m.media-amazon.com/images/M/MV5BMTU4MjIwMTcyMl5BMl5BanBnXkFtZTYwMTYwNDA3._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '5.6',
    },
    {
      id: 'tt9419884',
      title: 'Doctor Strange in the Multiverse of Madness',
      image:
        'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.0',
    },
    {
      id: 'tt12593682',
      title: 'Bullet Train',
      image:
        'https://m.media-amazon.com/images/M/MV5BMDU2ZmM2OTYtNzIxYy00NjM5LTliNGQtN2JmOWQzYTBmZWUzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.5',
    },
    {
      id: 'tt7144666',
      title: 'The Black Phone',
      image:
        'https://m.media-amazon.com/images/M/MV5BOWVmNTBiYTUtZWQ3Yi00ZDlhLTgyYjUtNzBhZjM3YjRiNGRkXkEyXkFqcGdeQXVyNzYyOTM1ODI@._V1_Ratio0.6763_AL_.jpg',
      imDbRating: '7.0',
    },
  ],
  tvSeriesInfo: null,
  tvEpisodeInfo: null,
  errorMessage: null,
};

export default info;
